### ISSUE TITLE
consider using the full hostname

### ISSUE THREAD

**Issue by Offirmo** [adamhalasz/uniqid#2]
In my company, all machines in Paris office have a name that starts with "PAR". Taking the 3 first letters is not enough ^^

**Comment by adamhalasz** [comment]
@Offirmo that makes sense :P I will think about a better way. @khalilTN is right, the mac address would be the ultimate solution for making the ID's completely unique however I also want to make them small in size.

**Comment by khalilTN** [comment]
@adamhalasz You can generate a hash, maybe MD5

**Comment by isayme** [comment]
How about hash hostname ? like md5 or something else.

Event we can use full hostname, we should think about that hostname can contain other characters beyond alphanumeric characters.

**Comment by khalilTN** [comment]
I thought about md5 too, but md5 generates 32 hexadecimal digits, the uid will be long and that violates @adamhalasz  length constraint.
In my own, they can be 2 procedures :
- The first one for browsers, generated uid is based on the current time (like v1).
- The second one for node apps (advanced one), based on mac addresses, process ids and current time. 
What do you think ?

**Comment by isayme** [comment]
we can still use first 3 letters of md5 result. 
however, mac address is another option.

and how about hash current time ?

**Comment by khalilTN** [comment]
i think using the first 3 letters would rize the collision probability

**Comment by adamhalasz** [comment]
Hey guys I added MAC Address support to v3. It's a bit longer but still just 18 bytes. There are also 2 new weaker functions with shorter length: `uniqid.process()` and `uniqid.time()`

@Offirmo I believe this solves your issue.

Thanks,
Adam
