### ISSUE TITLE
Error when network address is not available

### ISSUE THREAD

**Issue by toaniel** [adamhalasz/uniqid#5]
Hello, I'm using uniqid. If I turn my wifi off (no network connection), it exits with an error I can't handle.

```
$ gulp command
 
/Users/psyx/psyxgen/node_modules/uniqid/index.js:11
require('macaddress').one(function(error, macAddress){ if(error) throw error; address = macAddress; });
                                                                 ^
no interfaces found
$
```
                              
Is there a workaround? Thanks.

**Comment by adamhalasz** [comment]
Hi @toaniel 

Thanks for letting me know. I just tested it on OS X 10.11.4 without WiFi and it works fine. It is strange that it doesn't give you a mac address. Can you tell me what OS are you using? 

I'm releasing a new version soon that will handle these errors more gracefully by the way.

Thanks,
Adam

**Comment by adamhalasz** [comment]
@toaniel please give it a try with the new `v3.1.0`

**Comment by adamhalasz** [comment]
Hey @toaniel I'm closing this for now. Let me know if you still have this issue.
