### ISSUE TITLE
Application breaks when using strict mode because of dependency macaddress

### ISSUE THREAD

**Issue by nerdbeere** [adamhalasz/uniqid#6]
Hey there,

I use `uniqid` in my project but it breaks because of your dependency to `macaddress` when using strict mode.
See this issue here: https://github.com/scravy/node-macaddress/issues/7

**Comment by adamhalasz** [comment]
Hey @nerdbeere 

Uh oh lots of issues coming from this dependecy haha 
Let's see what the author will say in his response.

Thanks,
Adam

**Comment by nerdbeere** [comment]
It doesn't look like he's caring much. 
I think it would be really cool for `uniqid` if it wouldn't rely on any dependencies.

**Comment by adamhalasz** [comment]
Hi everyone, I removed the macaddress dependency in the new `v5.0.0`, so this issue should be fixed. And sorry for the late response.
