### ISSUE TITLE
dependency macaddress has a global leak

### ISSUE THREAD

**Issue by defunctzombie** [adamhalasz/uniqid#8]
They have fixed it (https://github.com/scravy/node-macaddress/commit/67e7f938c3acc90d5950c88b749fd6a15eb401db) but have not released a new version for a long time.

Would be nice to either publish a fork of theirs (if the author isn't going to update) and depend on that until there is an actual update.

Issue asking them to release a new version:
https://github.com/scravy/node-macaddress/issues/9

**Comment by anshu300** [comment]
how uniqid id genrate only number formate and length 8 to 10

**Comment by harshitgupta** [comment]
The issue has been fixed [https://github.com/scravy/node-macaddress/commits/master](url) 0.2.9 released. Please update the dependency version in this repo. Thanks

**Comment by ntwb** [comment]
The link above doesn't work here's that link https://github.com/scravy/node-macaddress/commits/master, also the `2.9.0` version has not been released to nmjs.com nor tagged `2.9.0` in the repo

https://www.npmjs.com/package/macaddress?activeTab=versions

**Comment by anajavi** [comment]
The macaddress can also be acquired in newer node releases with:
```javascript
require('os').networkInterfaces()
```
So dropping support for older node would help here.

**Comment by eladcandroid** [comment]
And here's the "npm audit" critical issue:
![screen shot 2018-05-23 at 11 28 22](https://user-images.githubusercontent.com/13297000/40413235-fe656a84-5e7d-11e8-8942-8fa74caa85e4.png)

**Comment by adamhalasz** [comment]
Hi everyone, I removed the macaddress dependency in the new `v5.0.0`, so this issue should be fixed. And sorry for the late response.

<img width="994" alt="screen shot 2018-06-03 at 4 59 29 pm" src="https://user-images.githubusercontent.com/839018/40887904-f7d498ae-674f-11e8-91f8-2a489f6ee3eb.png">

Let me know if there are any other issues.

Thanks,
Adam
